spring.datasource.url=jdbc:mysql://127.0.0.1:3306/alistamento_militar
spring.datasource.username=root
spring.datasource.password=fitodb
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Consulta nossas variáveis de ambiente - JWT_SECRET

api.security.token.secret=${JWT_SECRET:mq-secret-key}

